# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  generate_and_publish_docs:
  
    runs-on: ubuntu-latest
    
    name: Generate and publish the docs
    
    steps:
    - uses: actions/checkout@v1
      name: Checkout code
    - uses: nunit/docfx-action@v2.4.0
      name: Build Documentation
      with:
        args: path/to/your/docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
      
  publish:
  
    name: build, pack & publish
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            5.0.x
            6.0.x
            7.0.x
            8.0.x
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: SimpleAzureQueueConsumer/SimpleAzureQueueConsumer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
